# Fechatter Frontend - Development Configuration
# 开发环境：适合Vercel部署的开发版本

app:
  name: "Fechatter"
  version: "1.0.0"
  environment: "development"
  debug: true

# 前端服务器配置
frontend:
  port: 5173 # 本地开发端口
  host: "0.0.0.0" # 允许外部访问

# API配置 - 使用实际后端服务
api:
  base_url: "https://hook-nav-attempt-size.trycloudflare.com/api"
  timeout: 30000
  retry_attempts: 3
  retry_delay: 1000

# CORS配置
cors:
  enabled: true
  allowed_origins:
  - "http://localhost:5173"
  - "https://*.vercel.app" # 支持Vercel域名
  - "https://hook-nav-attempt-size.trycloudflare.com"

# 开发工具配置
dev_tools:
  hot_reload: true
  source_maps: true
  vue_devtools: false # 在Vercel上禁用
  performance_monitor: true
  error_overlay: true

# 功能开关
features:
  sse_enabled: true
  file_upload: true
  emoji_picker: true
  message_reactions: true
  typing_indicators: true
  presence_system: true
  analytics: false # 开发环境禁用分析

# SSE配置
sse:
  endpoint: "/events"
  reconnect_interval: 5000
  max_reconnect_attempts: 10
  heartbeat_interval: 30000

# 文件上传配置
file_upload:
  max_size: 10485760 # 10MB
  allowed_types:
  - "image/*"
  - "text/*"
  - "application/pdf"
  - "application/msword"
  - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# 性能配置
performance:
  lazy_loading: true
  image_optimization: true
  chunk_splitting: true
  preload_critical: true

# 安全配置
security:
  csp_enabled: true
  xss_protection: true
  content_type_nosniff: true

# 日志配置
logging:
  level: "debug"
  console_output: true
  remote_logging: false

# 测试账户配置（开发环境专用）
test_accounts:
  super:
    email: "super@test.com"
    password: "password"
    name: "Super User"
    role: "admin"
    workspace_id: 2
    user_id: 2
    description: "超级管理员测试账户"
  admin:
    email: "admin@test.com"
    password: "password"
    name: "Admin User"
    role: "admin"
    workspace_id: 2
    user_id: 3
    description: "管理员测试账户"

# 构建配置
build:
  minify: false # 开发构建不压缩，便于调试
  source_map: true
  analyze_bundle: false
  target: "esnext"

# 环境变量
env_vars:
  VITE_API_URL: "https://hook-nav-attempt-size.trycloudflare.com/api"
  VITE_APP_ENV: "development"
  VITE_SSE_ENDPOINT: "/events"
  VITE_ENABLE_DEBUG: "true"
