# Fechatter Frontend - Development Configuration
# 开发环境：通过Vite代理访问HTTPS后端服务

app:
  name: "Fechatter"
  version: "1.0.0"
  environment: "development"
  debug: true

# 前端服务器配置
frontend:
  port: 5173 # Vite默认端口
  host: "localhost"
  hmr_port: 1421

# API配置 - 开发环境通过Vite代理访问HTTPS后端
api:
  # 开发环境使用相对路径，通过Vite代理到HTTPS后端
  gateway_url: "http://localhost:5173"

  # 使用相对路径，让Vite代理处理SSL证书问题
  base_url: "/api"
  file_url: "/files"
  sse_url: "/events"
  notify_url: "/notify"

  # 请求配置
  timeout: 15000
  max_retries: 3
  retry_delay: 1000

# CORS配置 - 支持本地开发和Vercel部署
cors:
  enabled: true
  origins:
  - "http://localhost:5173" # Vite开发端口
  - "http://localhost:1420" # 备用端口
  - "http://127.0.0.1:5173"
  - "https://fechatter-frontend-cahw21vjh-zhkevin46-gmailcoms-projects.vercel.app"
  - "https://*.vercel.app" # 所有Vercel部署域名
  credentials: true

# 开发工具
dev_tools:
  enable_devtools: true
  enable_source_maps: true
  hot_reload: true

# 日志配置
logging:
  level: "debug"
  enable_network_logs: true
  enable_api_logs: true

# 测试账户配置 - 开发环境快速登录
test_accounts:
- email: "test@fechatter.com"
  password: "test123"
  name: "Test User"
  description: "主要测试账户"
- email: "dev@fechatter.com"
  password: "dev123"
  name: "Dev User"
  description: "开发测试账户"
- email: "admin@fechatter.com"
  password: "admin123"
  name: "Admin User"
  description: "管理员测试账户"
