# Fechatter Frontend - Development Configuration
# 开发环境：前端通过Vite代理访问后端服务

app:
  name: "Fechatter"
  version: "1.0.0"
  environment: "development"
  debug: true

# 前端服务器配置
frontend:
  port: 5173 # Vite默认端口
  host: "localhost"
  hmr_port: 1421

# API配置 - 通过Vite代理访问，避免CORS问题
api:
  # Gateway地址 - 仅用于显示和日志
  gateway_url: "http://45.77.178.85:8080"

  # 开发环境使用相对路径，通过Vite代理到远程Gateway
  base_url: "/api" # 通过Vite代理到 45.77.178.85:8080/api
  file_url: "/files" # 通过Vite代理到 45.77.178.85:8080/files
  sse_url: "/events" # 通过Vite代理到 45.77.178.85:8080/events
  notify_url: "/notify" # 通过Vite代理到 45.77.178.85:8080/notify

  # 请求配置
  timeout: 15000
  max_retries: 3
  retry_delay: 1000

# CORS配置 - 通过代理处理，无需前端配置
cors:
  enabled: true
  origins:
  - "http://localhost:5173" # Vite开发端口
  - "http://localhost:1420" # 备用端口
  - "http://127.0.0.1:5173"
  credentials: true

# 开发工具
dev_tools:
  enable_devtools: true
  enable_source_maps: true
  hot_reload: true

# 日志配置
logging:
  level: "debug"
  enable_network_logs: true
  enable_api_logs: true
