# Fechatter Frontend - Production SSL Configuration
# 生产环境：使用正式SSL证书的域名

app:
  name: "Fechatter"
  version: "1.0.0"
  environment: "production"
  debug: false

# 前端服务器配置（生产环境由Vercel管理）
frontend:
  port: 3000
  host: "0.0.0.0"

# API配置 - 生产环境使用正式SSL域名
api:
  # 使用正式SSL域名
  gateway_url: "https://api.fechatter.com"

  # 生产环境使用正式域名API
  base_url: "https://api.fechatter.com/api"
  file_url: "https://api.fechatter.com/files"
  sse_url: "https://api.fechatter.com/events"
  notify_url: "https://api.fechatter.com/notify"

  # 请求配置
  timeout: 15000
  max_retries: 3
  retry_delay: 1000

# CORS配置 - 生产环境
cors:
  enabled: true
  origins:
  - "https://app.fechatter.com" # 主前端域名
  - "https://fechatter.vercel.app" # Vercel默认域名
  - "https://*.vercel.app" # 所有Vercel部署域名
  credentials: true

# 开发工具（生产环境禁用）
dev_tools:
  enable_devtools: false
  enable_source_maps: false
  hot_reload: false

# 日志配置
logging:
  level: "warn"
  enable_network_logs: false
  enable_api_logs: false

# 测试账户配置 - 生产环境保留用于演示
test_accounts:
- email: "demo@fechatter.com"
  password: "demo123"
  name: "Demo User"
  description: "演示账户"
- email: "guest@fechatter.com"
  password: "guest123"
  name: "Guest User"
  description: "访客账户"
