# Fechatter Frontend - Production Configuration
# 生产环境：与开发环境保持一致的配置

app:
  name: "Fechatter"
  version: "1.0.0"
  environment: "production"
  debug: true

# 前端服务器配置
frontend:
  port: 5173 # Vite默认端口
  host: "localhost"
  hmr_port: 1421

# API配置 - 生产环境也使用相对路径，通过Vite/Vercel代理访问HTTPS后端
api:
  # 生产环境使用相对路径，通过代理到HTTPS后端
  gateway_url: "http://localhost:5173"

  # 使用相对路径，让代理处理SSL证书问题（与开发环境路径保持一致）
  base_url: "/api"
  file_url: "/files"
  sse_url: "/events"
  notify_url: "/notify"

  # 请求配置
  timeout: 15000
  max_retries: 3
  retry_delay: 1000

# CORS配置 - 注意：实际CORS由后端nginx控制，这里仅作为前端参考
cors:
  enabled: true
  origins:
  # 动态Vercel域名通配符（后端nginx使用正则匹配）
  - "https://*.vercel.app"
  - "https://fechatter_frontend.vercel.app"
  credentials: true

# 开发工具（生产环境禁用）
dev_tools:
  enable_devtools: false
  enable_source_maps: false
  hot_reload: false

# 日志配置
logging:
  level: "warn"
  enable_network_logs: false
  enable_api_logs: false

# 测试账户配置 - 生产环境也保留用于演示
test_accounts:
- email: "test@fechatter.com"
  password: "test123"
  name: "Test User"
  description: "演示账户"
- email: "dev@fechatter.com"
  password: "dev123"
  name: "Dev User"
  description: "开发演示账户"
- email: "admin@fechatter.com"
  password: "admin123"
  name: "Admin User"
  description: "管理员演示账户"
- email: "super@test.com"
  password: "password"
  name: "Super User"
  description: "超级用户测试账户"
